# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-15 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='angle',
        ),
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.CharField(blank=True, default=b'latest', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='signature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='y',
            field=models.IntegerField(),
        ),
    ]
